### ISSUE TITLE
Interested in cleaning up Dockerfile and including docker-compose.yml

### ISSUE THREAD

**Issue by jason-riddle** [mkaczanowski/packer-builder-arm#17]
I've been following this project very closely and I've been working to simplify the Dockerfile config and use docker-compose to orchestrate building. Would there be interest in accepting this back as a PR? Here's what I have so far for building the raspbian image. This assumes you have the packer-builder-arm repo locally available:

`docker/Dockerfile`

```dockerfile
FROM multiarch/qemu-user-static:register AS register
FROM golang:1.13-buster AS builder

# Install git
RUN apt-get update \
    && apt-get install -y --no-install-recommends git

# Prepare build directory
WORKDIR /build

# Build packer-builder-arm
RUN git clone https://github.com/mkaczanowski/packer-builder-arm \
    && cd packer-builder-arm \
    && GO111MODULE=on go build -o packer-builder-arm

FROM ubuntu:18.04

ARG PACKER_VERSION=1.4.5

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends sudo ca-certificates make wget unzip kpartx qemu-user-static

# Install packer
RUN wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip 2>/dev/null \
    && unzip -o /tmp/packer.zip -d /usr/local/bin \
    && rm -f /tmp/packer.zip

# Copy relevant binaries
COPY --from=builder  /build/packer-builder-arm/packer-builder-arm /usr/local/bin/packer-builder-arm
COPY --from=register /register /register
COPY --from=register /qemu-binfmt-conf.sh /qemu-binfmt-conf.sh

# Prepare workspace
WORKDIR /workspace
```

`docker-compose.yml`

```yml
version: '3.5'

services:
  packer:
    image: local/packer-builder-arm
    build: docker/
    volumes:
      - .:/workspace
      - /dev:/dev
    privileged: true
    command:
      - /bin/sh
      - -c
      - "sudo /register 2>/dev/null && make packer-builder-arm/boards/raspberry-pi/raspbian.json"
```

I then have a make command to help with building

`Makefile`

```make
build:
	COMPOSE_HTTP_TIMEOUT=5 docker-compose up \
	--build \
	--force-recreate \
	--abort-on-container-exit \
	--remove-orphans
```
